### ISSUE TITLE
Failed to "azd up"in the template

### ISSUE THREAD

**Issue by zzhxiaofeng** [lopezleandro03/azd-devcenter#4]
**Describe the issue:**
When run `azd up` according to [README.md](https://github.com/lopezleandro03/azd-devcenter/blob/main/README.md), the gitHub source control uri is invalid. The error is shown as following:
![image](https://github.com/lopezleandro03/azd-devcenter/assets/20970631/b963a86e-9e38-4c17-a49f-fcbde3801995)

**Repro Steps:**
1.Create an empty folder and run `azd init -t https://github.com/lopezleandro03/azd-devcenter` under the folder. Open code with vscode.
2.Define the following environment variables:
```Bash
# Bash
export GITHUB_TOKEN=<your_github_token>
export GIT_OWNER=<git_owner> # Use 'Azure' to use Microsoft official catalog
export GIT_REPO=<git_repo> # Use 'deployment-environments' to use Microsoft official catalog
```
3.Run `azd up`.

**Expected behavior:**
It will run `azd up` successfully.

@lopezleandro03, @gkulin for notification.

**Comment by lopezleandro03** [comment]
Hi @zzhxiaofeng, what values are you using for GIT_OWNER and GIT_REPO? This should be a valid GitHub handle and repo. The example values provided in comments would point to the Microsoft ADE repo:

https://github.com/Azure/deployment-environments

**Comment by zzhxiaofeng** [comment]
@lopezleandro03 The values I used is shown as following:
```
export GIT_OWNER="Azure"
export GIT_REPO="deployment-environments"
```

**Comment by lopezleandro03** [comment]
@zzhxiaofeng, the variable names were misspelled in the documentation. I should be `GITHUB_*`  rather than `GIT_*`.
I have submitted and completed a PR(#6) to fix it. Please get the latest and try again.

**Comment by lopezleandro03** [comment]
@zzhxiaofeng, added pre-provision hook to ensure the env vars exists before attempting to deploy the infra (https://github.com/lopezleandro03/azd-devcenter/pull/8)

**Comment by zzhxiaofeng** [comment]
@lopezleandro03 Thank you, the issue has been resolved. But when I follow next step to open [`Developer Portal`](https://devportal.microsoft.com/), it will has permission question as following:
![MicrosoftTeams-image (1)](https://github.com/lopezleandro03/azd-devcenter/assets/20970631/b5e690c3-4da7-4e6c-bcb9-50774c2bf5d6)

**Comment by lopezleandro03** [comment]
HI @zzhxiaofeng, are you logging to the Developer Portal with the same account that you use with `azd` (inherited by Terraform) to deploy all resources? 

Another thing to look is if you have multiple tenants, make sure you are logging to the right tenant.

**Comment by zzhxiaofeng** [comment]
@lopezleandro03 I use the same account to login to `Developer Portal`. we have only one tenant and the tenant name is `Microsoft`.

**Comment by lopezleandro03** [comment]
@zzhxiaofeng, Can you confirm that you used the [Azure/deployment-environments](https://github.com/Azure/deployment-environments) repository as a catalog? You need to have catalog items imported in Dev Box before you can see the option to deploy environments from the portal. Please go to Dev Center --> Catalogs and ensure that the catalog synched properly (should be green).

<img width="908" alt="image" src="https://github.com/lopezleandro03/azd-devcenter/assets/12474226/15da928d-a86b-4331-a7fc-14f1e6cb99ac">

Additionally, you should have the the `Deployment Environments User` role assigned at a project level. All that is baked into Terraform, so should be there if the deployment didn't fail.

**Comment by lopezleandro03** [comment]
@zzhxiaofeng, based on today's discussion we should be good to go as you manage to deploy e2e and get to the Dev Portal after forking catalog repo. Please confirm that this issue can be closed.

**Comment by v-jiaodi** [comment]
> @lopezleandro03 Thank you, the issue has been resolved. But when I follow next step to open [`Developer Portal`](https://devportal.microsoft.com/), it will has permission question as following: ![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/20970631/265620773-b5e690c3-4da7-4e6c-bcb9-50774c2bf5d6.png)

@lopezleandro03  Adding `Azure Authorize` for `GITHUB_TOKEN`,  it can work normally. Do you think this is the root cause? If so, suggest adding an explanation in `README.md` regarding the need to add `Azure Authorize` when creating `GITHUB_TOKEN`.
![image](https://github.com/lopezleandro03/azd-devcenter/assets/80496810/8604082f-2e08-46aa-b83a-06607e1d6f3c)

**Comment by lopezleandro03** [comment]
Hi @zzhxiaofeng, I am not sure about that, the specific how PAT tokens go beyond the scope of this project and I can't replicate your issue.

This sample repo I provided is public, therefore, a PAT token with `repo` read permissions should work. I added a link to `How to manage GitHub PATs` to the README.md (#9 )

**Comment by zzhxiaofeng** [comment]
@lopezleandro03 We open [Developer Portal](https://devportal.microsoft.com/) succesfully.  But when we create an environment, it will return an error as following. Please have a look when you are free.
![image](https://github.com/lopezleandro03/azd-devcenter/assets/20970631/196b2671-d725-4765-a5fc-f072d4ffbbb6)

**Comment by lopezleandro03** [comment]
Hi @zzhxiaofeng, this is expected. You tried to deploy an environment that uses `Terraform` and the `processor`. Terraform support is in private preview and has to be activated by submitting a form.

If you pick an ARM based environment it should work.

This is beyond the scope of this repo.
